/**
 * Aether Learning Collection System
 *
 * This composable helps collect anonymized learnings about documentation
 * improvements to help improve Aether for everyone.
 *
 * PRIVACY FIRST:
 * - Completely opt-in
 * - Only shares documentation changes
 * - No code or sensitive data
 * - User reviews before sending
 */

import { useRuntimeConfig } from '#app';

interface Learning {
    id: string;
    timestamp: string;
    type:
        | 'api-clarification'
        | 'error-solution'
        | 'pattern-improvement'
        | 'example-added'
        | 'other';
    file: string;
    diff?: string;
    context?: string;
    aetherVersion?: string;
}

export const useAetherLearnings = () => {
    const config = useRuntimeConfig();

    // Check if user has opted in
    const isOptedIn = ref(false);

    // Collection endpoint (you'd need to set this up)
    const LEARNING_ENDPOINT = 'https://aether-learnings.lovelace.ai/api/submit';

    /**
     * Track a documentation improvement
     */
    async function trackLearning(learning: Partial<Learning>) {
        if (!isOptedIn.value) return;

        const payload: Learning = {
            id: crypto.randomUUID(),
            timestamp: new Date().toISOString(),
            aetherVersion: String(config.public.appVersion || 'unknown'),
            type: 'other',
            file: '',
            ...learning,
        };

        // Store locally first
        const learnings = JSON.parse(localStorage.getItem('aether-learnings') || '[]');
        learnings.push(payload);
        localStorage.setItem('aether-learnings', JSON.stringify(learnings));

        // Show notification
        if (
            window.confirm(
                "You've made a documentation improvement! Would you like to share it to help other Aether users?"
            )
        ) {
            await submitLearning(payload);
        }
    }

    /**
     * Submit a learning to the collection endpoint
     */
    async function submitLearning(learning: Learning) {
        try {
            // In real implementation, you'd send to your endpoint
            console.log('Would submit learning:', learning);

            // For now, create a GitHub issue URL
            const issueBody = encodeURIComponent(`
## Automated Learning Report

**Type**: ${learning.type}
**File**: ${learning.file}
**Aether Version**: ${learning.aetherVersion}

### Context
${learning.context || 'No context provided'}

### Change
\`\`\`diff
${learning.diff || 'No diff available'}
\`\`\`

---
*This report was automatically generated by the Aether Learning Collection system*
            `);

            const issueUrl = `https://github.com/Lovelace-AI/aether/issues/new?title=Learning:+${learning.type}&body=${issueBody}&labels=documentation-improvement,automated`;

            window.open(issueUrl, '_blank');
        } catch (error) {
            console.error('Failed to submit learning:', error);
        }
    }

    /**
     * Get all pending learnings
     */
    function getPendingLearnings(): Learning[] {
        return JSON.parse(localStorage.getItem('aether-learnings') || '[]');
    }

    /**
     * Enable/disable learning collection
     */
    function setOptIn(value: boolean) {
        isOptedIn.value = value;
        localStorage.setItem('aether-learnings-optin', String(value));
    }

    // Check opt-in status on load
    onMounted(() => {
        isOptedIn.value = localStorage.getItem('aether-learnings-optin') === 'true';
    });

    return {
        trackLearning,
        getPendingLearnings,
        submitLearning,
        setOptIn,
        isOptedIn: readonly(isOptedIn),
    };
};
