export type ThemePresetId = 'lovelace-dark' | 'lovelace-light' | 'paper' | 'bloomberg' | 'slate';

export interface ThemePreset {
    id: ThemePresetId;
    label: string;
    mode: 'dark' | 'light';
    vuetifyTheme: {
        dark: boolean;
        colors: Record<string, string>;
    };
    dynamicTokens: Record<string, string>;
    scoreRamp: [string, string, string];
}

export const DEFAULT_THEME_ID: ThemePresetId = 'lovelace-dark';

export const THEME_PRESETS: ThemePreset[] = [
    {
        id: 'lovelace-dark',
        label: 'Lovelace Dark',
        mode: 'dark',
        vuetifyTheme: {
            dark: true,
            colors: {
                background: '#0a0a0a',
                surface: '#141414',
                'surface-variant': '#1c1c1c',
                primary: '#3fea00',
                secondary: '#003bff',
                warning: '#ff5c00',
                error: '#ef4444',
                info: '#003bff',
                success: '#3fea00',
                'on-background': '#e5e5e5',
                'on-surface': '#e5e5e5',
            },
        },
        dynamicTokens: {
            primary: '#3fea00',
            secondary: '#003bff',
            accent: '#003bff',
            background: '#0a0a0a',
            surface: '#141414',
            cardBackground: '#1e1e1e',
            panelBackground: '#111111',
            textPrimary: '#ffffff',
            textSecondary: '#a0aec0',
            textMuted: '#757575',
            hover: '#1e1e1e',
            border: '#2a2a2a',
            success: '#3fea00',
            warning: '#ff9f0a',
            error: '#ef4444',
            headerGradientStart: '#0a0a0a',
            headerGradientEnd: '#141414',
            primaryRgb: '63, 234, 0',
            fgRgb: '229, 229, 229',
            severityHigh: 'hsl(0 72% 51%)',
            severityMedium: 'hsl(36 100% 50%)',
            severityLow: 'hsl(226 100% 60%)',
            severitySuppressed: 'hsl(0 0% 60%)',
            severityHighRgb: '217, 70, 70',
            severityMediumRgb: '255, 159, 10',
            severityLowRgb: '51, 102, 255',
            severitySuppressedRgb: '153, 153, 153',
        },
        scoreRamp: ['#3366ff', '#ff9f0a', '#d94646'],
    },
    {
        id: 'lovelace-light',
        label: 'Lovelace Light',
        mode: 'light',
        vuetifyTheme: {
            dark: false,
            colors: {
                background: '#f5f8f5',
                surface: '#ffffff',
                'surface-variant': '#edf3ec',
                primary: '#2ea52a',
                secondary: '#0f3c8f',
                warning: '#d97706',
                error: '#dc2626',
                info: '#2563eb',
                success: '#2ea52a',
                'on-background': '#111827',
                'on-surface': '#111827',
            },
        },
        dynamicTokens: {
            primary: '#2ea52a',
            secondary: '#0f3c8f',
            accent: '#1d4ed8',
            background: '#f5f8f5',
            surface: '#ffffff',
            cardBackground: '#ffffff',
            panelBackground: '#edf3ec',
            textPrimary: '#111827',
            textSecondary: '#334155',
            textMuted: '#64748b',
            hover: '#e8f3e7',
            border: '#d4ded2',
            success: '#2ea52a',
            warning: '#d97706',
            error: '#dc2626',
            headerGradientStart: '#111827',
            headerGradientEnd: '#1f2937',
            primaryRgb: '46, 165, 42',
            fgRgb: '30, 41, 59',
            severityHigh: 'hsl(0 62% 50%)',
            severityMedium: 'hsl(36 100% 48%)',
            severityLow: 'hsl(226 80% 52%)',
            severitySuppressed: 'hsl(0 0% 45%)',
            severityHighRgb: '207, 64, 64',
            severityMediumRgb: '245, 158, 11',
            severityLowRgb: '59, 130, 246',
            severitySuppressedRgb: '115, 115, 115',
        },
        scoreRamp: ['#3b82f6', '#f59e0b', '#cf4040'],
    },
    {
        id: 'paper',
        label: 'Paper',
        mode: 'light',
        vuetifyTheme: {
            dark: false,
            colors: {
                background: '#f8f8f5',
                surface: '#ffffff',
                'surface-variant': '#f1f2ef',
                primary: '#0a4d8c',
                secondary: '#455a64',
                warning: '#d97706',
                error: '#b91c1c',
                info: '#2563eb',
                success: '#0f766e',
                'on-background': '#111827',
                'on-surface': '#111827',
            },
        },
        dynamicTokens: {
            primary: '#0a4d8c',
            secondary: '#455a64',
            accent: '#145da0',
            background: '#f8f8f5',
            surface: '#ffffff',
            cardBackground: '#ffffff',
            panelBackground: '#f1f2ef',
            textPrimary: '#111827',
            textSecondary: '#334155',
            textMuted: '#64748b',
            hover: '#ecefea',
            border: '#d8ddd6',
            success: '#0f766e',
            warning: '#d97706',
            error: '#b91c1c',
            headerGradientStart: '#10151c',
            headerGradientEnd: '#18212c',
            primaryRgb: '10, 77, 140',
            fgRgb: '30, 41, 59',
            severityHigh: 'hsl(0 62% 48%)',
            severityMedium: 'hsl(34 92% 45%)',
            severityLow: 'hsl(212 84% 42%)',
            severitySuppressed: 'hsl(0 0% 42%)',
            severityHighRgb: '197, 58, 58',
            severityMediumRgb: '217, 119, 6',
            severityLowRgb: '37, 99, 235',
            severitySuppressedRgb: '107, 114, 128',
        },
        scoreRamp: ['#2563eb', '#d97706', '#c53a3a'],
    },
    {
        id: 'bloomberg',
        label: 'Bloomberg',
        mode: 'dark',
        vuetifyTheme: {
            dark: true,
            colors: {
                background: '#0a0b0d',
                surface: '#121417',
                'surface-variant': '#1a1d22',
                primary: '#f59e0b',
                secondary: '#f97316',
                warning: '#f59e0b',
                error: '#ef4444',
                info: '#60a5fa',
                success: '#10b981',
                'on-background': '#f8fafc',
                'on-surface': '#f8fafc',
            },
        },
        dynamicTokens: {
            primary: '#f59e0b',
            secondary: '#f97316',
            accent: '#fbbf24',
            background: '#0a0b0d',
            surface: '#121417',
            cardBackground: '#1a1d22',
            panelBackground: '#101216',
            textPrimary: '#f8fafc',
            textSecondary: '#cbd5e1',
            textMuted: '#94a3b8',
            hover: '#1c2128',
            border: '#2a3340',
            success: '#10b981',
            warning: '#f59e0b',
            error: '#ef4444',
            headerGradientStart: '#06070a',
            headerGradientEnd: '#121417',
            primaryRgb: '245, 158, 11',
            fgRgb: '248, 250, 252',
            severityHigh: 'hsl(0 78% 56%)',
            severityMedium: 'hsl(39 95% 52%)',
            severityLow: 'hsl(221 90% 64%)',
            severitySuppressed: 'hsl(0 0% 58%)',
            severityHighRgb: '231, 85, 85',
            severityMediumRgb: '245, 158, 11',
            severityLowRgb: '96, 165, 250',
            severitySuppressedRgb: '148, 163, 184',
        },
        scoreRamp: ['#60a5fa', '#f59e0b', '#e75555'],
    },
    {
        id: 'slate',
        label: 'Slate',
        mode: 'dark',
        vuetifyTheme: {
            dark: true,
            colors: {
                background: '#111827',
                surface: '#1f2937',
                'surface-variant': '#273549',
                primary: '#34d399',
                secondary: '#60a5fa',
                warning: '#f59e0b',
                error: '#ef4444',
                info: '#60a5fa',
                success: '#34d399',
                'on-background': '#f8fafc',
                'on-surface': '#f8fafc',
            },
        },
        dynamicTokens: {
            primary: '#34d399',
            secondary: '#60a5fa',
            accent: '#2dd4bf',
            background: '#111827',
            surface: '#1f2937',
            cardBackground: '#273549',
            panelBackground: '#182234',
            textPrimary: '#f8fafc',
            textSecondary: '#cbd5e1',
            textMuted: '#94a3b8',
            hover: '#243247',
            border: '#32415a',
            success: '#34d399',
            warning: '#f59e0b',
            error: '#ef4444',
            headerGradientStart: '#0f172a',
            headerGradientEnd: '#1e293b',
            primaryRgb: '52, 211, 153',
            fgRgb: '248, 250, 252',
            severityHigh: 'hsl(0 72% 56%)',
            severityMedium: 'hsl(36 96% 52%)',
            severityLow: 'hsl(218 92% 64%)',
            severitySuppressed: 'hsl(0 0% 62%)',
            severityHighRgb: '228, 95, 95',
            severityMediumRgb: '245, 158, 11',
            severityLowRgb: '96, 165, 250',
            severitySuppressedRgb: '148, 163, 184',
        },
        scoreRamp: ['#60a5fa', '#f59e0b', '#e45f5f'],
    },
];

export const THEME_PRESETS_BY_ID = Object.fromEntries(
    THEME_PRESETS.map((preset) => [preset.id, preset])
) as Record<ThemePresetId, ThemePreset>;
